// <auto-generated />
using System;
using Javbuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Javbuddy.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20261006123418_Baseline")]
partial class _20261006123418_Baseline
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128");

        modelBuilder.Entity("Javbuddy.Models.Actor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("BirthDate")
                    .HasColumnType("TEXT");

                b.Property<int?>("Bust")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CupSize")
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("FavoritedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<int?>("HeightCm")
                    .HasColumnType("INTEGER");

                b.Property<int?>("Hips")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsFavorite")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsRetired")
                    .HasColumnType("INTEGER");

                b.Property<string>("JapaneseNameKana")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("JapaneseNameKanji")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("JellyfinPersonId")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<int?>("R18DevId")
                    .HasColumnType("INTEGER");

                b.Property<string>("R18DevName")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<int?>("Waist")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CupSize");

                b.HasIndex("HeightCm");

                b.HasIndex("IsFavorite");

                b.HasIndex("IsRetired");

                b.HasIndex("FirstName", "LastName")
                    .IsUnique();

                b.ToTable("Actors");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorAlbum", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ActorId", "Name")
                    .IsUnique();

                b.ToTable("ActorAlbums");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorAlias", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ActorId", "Name")
                    .IsUnique();

                b.ToTable("ActorAliases");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorCupSizePeriod", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<string>("CupSize")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("EffectiveFrom")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ActorId", "EffectiveFrom")
                    .IsUnique();

                b.ToTable("ActorCupSizePeriods");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorImage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<double?>("CropHeight")
                    .HasColumnType("REAL");

                b.Property<double?>("CropWidth")
                    .HasColumnType("REAL");

                b.Property<double?>("CropX")
                    .HasColumnType("REAL");

                b.Property<double?>("CropY")
                    .HasColumnType("REAL");

                b.Property<string>("SourceExtension")
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("SourceLastWriteUtc")
                    .HasColumnType("TEXT");

                b.Property<long>("SourceLength")
                    .HasColumnType("INTEGER");

                b.Property<string>("SourceMovieCode")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<Guid?>("SourceStorageId")
                    .HasColumnType("TEXT");

                b.Property<string>("SourceUrl")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<Guid>("StorageId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Variant")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ActorId", "Variant")
                    .IsUnique();

                b.ToTable("ActorImages");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorPhoto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("AlbumId")
                    .HasColumnType("INTEGER");

                b.Property<double?>("AspectRatio")
                    .HasColumnType("REAL");

                b.Property<Guid>("FullStorageId")
                    .HasColumnType("TEXT");

                b.Property<string>("SourceExtension")
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.Property<Guid?>("SourceStorageId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("ThumbStorageId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UploadedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AlbumId");

                b.HasIndex("ActorId", "UploadedAt");

                b.ToTable("ActorPhotos");
            });

        modelBuilder.Entity("Javbuddy.Models.ApexActor", b =>
            {
                b.Property<int>("ApexId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.HasKey("ApexId", "ActorId");

                b.HasIndex("MovieId", "ActorId");

                b.ToTable("ApexActors");
            });

        modelBuilder.Entity("Javbuddy.Models.ApexEffectiveActor", b =>
            {
                b.Property<int>("ApexId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.HasKey("ApexId", "ActorId");

                b.HasIndex("ActorId", "ApexId");

                b.HasIndex("MovieId", "ActorId");

                b.ToTable("ApexEffectiveActors");
            });

        modelBuilder.Entity("Javbuddy.Models.ApexPlaybackSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<double>("LeadInSeconds")
                    .HasColumnType("REAL");

                b.Property<double>("TailSeconds")
                    .HasColumnType("REAL");

                b.HasKey("Id");

                b.ToTable("ApexPlaybackSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.ApexTag", b =>
            {
                b.Property<int>("ApexId")
                    .HasColumnType("INTEGER");

                b.Property<int>("TagId")
                    .HasColumnType("INTEGER");

                b.HasKey("ApexId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("ApexTags");
            });

        modelBuilder.Entity("Javbuddy.Models.CachedImage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<int>("Index")
                    .HasColumnType("INTEGER");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<long?>("SceneEndMs")
                    .HasColumnType("INTEGER");

                b.Property<long?>("SceneStartMs")
                    .HasColumnType("INTEGER");

                b.Property<string>("SourceIdentity")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("SourceLastWriteUtc")
                    .HasColumnType("TEXT");

                b.Property<long>("SourceLength")
                    .HasColumnType("INTEGER");

                b.Property<string>("SourceUrl")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<Guid>("StorageId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Variant")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Code", "Role", "Index", "Variant")
                    .IsUnique();

                b.ToTable("CachedImages");
            });

        modelBuilder.Entity("Javbuddy.Models.DeletedMovie", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CanonicalKey")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaTitle")
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedCode")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("PreviousStatus")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CanonicalKey");

                b.HasIndex("DeletedAt");

                b.HasIndex("NormalizedCode")
                    .IsUnique();

                b.ToTable("DeletedMovies");
            });

        modelBuilder.Entity("Javbuddy.Models.DeoVrGroup", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("FilterJson")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int>("Position")
                    .HasColumnType("INTEGER");

                b.Property<bool>("SortDescending")
                    .HasColumnType("INTEGER");

                b.Property<string>("SortField")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("DeoVrGroups");

                b.HasData(
                    new
                    {
                        Id = 1,
                        FilterJson = "{}",
                        Name = "All movies",
                        Position = 0,
                        SortDescending = true,
                        SortField = "added"
                    });
            });

        modelBuilder.Entity("Javbuddy.Models.DeoVrSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("DeoVrSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.DiscoveredMovieCandidate", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ActressNames")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("CoverImageUrl")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("FirstSeenAt")
                    .HasColumnType("TEXT");

                b.Property<string>("GalleryImageUrls")
                    .IsRequired()
                    .HasMaxLength(8000)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsUpcoming")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("LastSeenAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("ReleaseDate")
                    .HasColumnType("TEXT");

                b.Property<string>("SourceName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("Studio")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("DiscoveredMovieCandidates");
            });

        modelBuilder.Entity("Javbuddy.Models.DiscoverySourceSetting", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("SourceName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SourceName")
                    .IsUnique();

                b.ToTable("DiscoverySourceSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.HighlightActor", b =>
            {
                b.Property<int>("HighlightId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.HasKey("HighlightId", "ActorId");

                b.HasIndex("MovieId", "ActorId");

                b.ToTable("HighlightActors");
            });

        modelBuilder.Entity("Javbuddy.Models.HighlightEffectiveActor", b =>
            {
                b.Property<int>("HighlightId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.HasKey("HighlightId", "ActorId");

                b.HasIndex("ActorId", "HighlightId");

                b.HasIndex("MovieId", "ActorId");

                b.ToTable("HighlightEffectiveActors");
            });

        modelBuilder.Entity("Javbuddy.Models.HighlightTag", b =>
            {
                b.Property<int>("HighlightId")
                    .HasColumnType("INTEGER");

                b.Property<int>("TagId")
                    .HasColumnType("INTEGER");

                b.HasKey("HighlightId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("HighlightTags");
            });

        modelBuilder.Entity("Javbuddy.Models.IgnoredTag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("MatchMode")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Value", "MatchMode")
                    .IsUnique();

                b.ToTable("IgnoredTags");
            });

        modelBuilder.Entity("Javbuddy.Models.JavinizerSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ApiToken")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("BaseUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("JavinizerSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.JellyfinSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ApiKey")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("BaseUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("ExternalUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("LastLinkSyncAt")
                    .HasColumnType("TEXT");

                b.Property<int?>("LastLinkSyncChecked")
                    .HasColumnType("INTEGER");

                b.Property<int?>("LastLinkSyncMatched")
                    .HasColumnType("INTEGER");

                b.Property<string>("SelectedLibraryNames")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("JellyfinSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.LocalLibrarySettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("RootPaths")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("LocalLibrarySettings");
            });

        modelBuilder.Entity("Javbuddy.Models.MediaInfoSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("MediaInfoSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.MinnanoAvSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("BaseUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("LastEnrichSummary")
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("LastEnrichedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("OverwriteExisting")
                    .HasColumnType("INTEGER");

                b.Property<int>("RequestDelayMs")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("MinnanoAvSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.Movie", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("CleanupBlacklisted")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("CleanupSnoozedUntil")
                    .HasColumnType("TEXT");

                b.Property<bool>("ClipActorsStale")
                    .HasColumnType("INTEGER");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("FavoritedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("FileAddedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("FileCount")
                    .HasColumnType("INTEGER");

                b.Property<bool>("HasBrokenBFrames")
                    .HasColumnType("INTEGER");

                b.Property<bool>("HasUnmatchedActors")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsFavorite")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("JellyfinCheckedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("JellyfinItemId")
                    .HasColumnType("TEXT");

                b.Property<string>("JellyfinLibraryId")
                    .HasColumnType("TEXT");

                b.Property<string>("JellyfinLibraryName")
                    .HasColumnType("TEXT");

                b.Property<string>("JellyfinServerId")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("LastReviewedAt")
                    .HasColumnType("TEXT");

                b.Property<long?>("LocalFileSizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaAspectRatio")
                    .HasColumnType("TEXT");

                b.Property<int?>("MediaAudioAlternateGroup")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MediaAudioBitRateKbps")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaAudioBitRateMode")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaAudioChannelLayout")
                    .HasColumnType("TEXT");

                b.Property<int?>("MediaAudioChannels")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaAudioCodec")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaAudioCodecId")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaAudioCompressionMode")
                    .HasColumnType("TEXT");

                b.Property<bool?>("MediaAudioDefault")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaAudioFormatInfo")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaAudioFormatSettings")
                    .HasColumnType("TEXT");

                b.Property<double?>("MediaAudioFrameRate")
                    .HasColumnType("REAL");

                b.Property<int?>("MediaAudioSamplingRateHz")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaAudioStreamId")
                    .HasColumnType("TEXT");

                b.Property<long?>("MediaAudioStreamSizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MediaBitDepth")
                    .HasColumnType("INTEGER");

                b.Property<double?>("MediaBitsPerPixelFrame")
                    .HasColumnType("REAL");

                b.Property<string>("MediaChromaSubsampling")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaCodecConfigurationBox")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaColorPrimaries")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaColorRange")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaColorSpace")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaContainerCodecId")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaContainerCodecIdCompatible")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaContainerFormat")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaContainerFormatProfile")
                    .HasColumnType("TEXT");

                b.Property<double?>("MediaDurationSeconds")
                    .HasColumnType("REAL");

                b.Property<string>("MediaEncodingSettings")
                    .HasColumnType("TEXT");

                b.Property<double?>("MediaFrameRate")
                    .HasColumnType("REAL");

                b.Property<double?>("MediaFrameRateMax")
                    .HasColumnType("REAL");

                b.Property<double?>("MediaFrameRateMin")
                    .HasColumnType("REAL");

                b.Property<string>("MediaFrameRateMode")
                    .HasColumnType("TEXT");

                b.Property<bool>("MediaHasSubtitleFile")
                    .HasColumnType("INTEGER");

                b.Property<bool>("MediaHasTrailerFile")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MediaHeight")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaImagesSignature")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaMatrixCoefficients")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("MediaNfoLastWriteUtc")
                    .HasColumnType("TEXT");

                b.Property<int?>("MediaOverallBitRateKbps")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaScanError")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaScanType")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaScanWarning")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("MediaScannedAt")
                    .HasColumnType("TEXT");

                b.Property<int?>("MediaSubtitleCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaTransferCharacteristics")
                    .HasColumnType("TEXT");

                b.Property<int?>("MediaVideoBitRateKbps")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaVideoCodec")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaVideoCodecId")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaVideoCodecIdInfo")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("MediaVideoFileLastWriteUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaVideoFileName")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaVideoFormatInfo")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaVideoFormatSettings")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaVideoProfile")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaVideoStreamId")
                    .HasColumnType("TEXT");

                b.Property<long?>("MediaVideoStreamSizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MediaWidth")
                    .HasColumnType("INTEGER");

                b.Property<string>("MediaWritingApplication")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaWritingLibrary")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaActresses")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaBackdropUrl")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaCoverUrl")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaDescription")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaDirector")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("MetaFetchedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaGenres")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaLabel")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaOriginalTitle")
                    .HasColumnType("TEXT");

                b.Property<double?>("MetaRatingScore")
                    .HasColumnType("REAL");

                b.Property<int?>("MetaRatingVotes")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("MetaReleaseDate")
                    .HasColumnType("TEXT");

                b.Property<int?>("MetaRuntimeMinutes")
                    .HasColumnType("INTEGER");

                b.Property<string>("MetaSeries")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaSourceName")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaSourceUrl")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaStudio")
                    .HasColumnType("TEXT");

                b.Property<string>("MetaTitle")
                    .HasColumnType("TEXT");

                b.Property<string>("NfoBaselineJson")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("NfoBaselineLastWriteUtc")
                    .HasColumnType("TEXT");

                b.Property<long?>("NfoBaselineSize")
                    .HasColumnType("INTEGER");

                b.Property<string>("NfoConflictDetails")
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<string>("NfoDriftKind")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("Notes")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<string>("UnmatchedActorNames")
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<string>("VrType")
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.HasIndex("IsFavorite");

                b.ToTable("Movies");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieActor", b =>
            {
                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.HasKey("MovieId", "ActorId");

                b.HasIndex("ActorId");

                b.ToTable("MovieActors");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieApex", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("FavoritedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsFavorite")
                    .HasColumnType("INTEGER");

                b.Property<double?>("LeadInSeconds")
                    .HasColumnType("REAL");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<double>("Seconds")
                    .HasColumnType("REAL");

                b.Property<double?>("TailSeconds")
                    .HasColumnType("REAL");

                b.HasKey("Id");

                b.HasIndex("MovieId", "Seconds");

                b.ToTable("MovieApexes");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieFile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AspectRatio")
                    .HasColumnType("TEXT");

                b.Property<int?>("AudioAlternateGroup")
                    .HasColumnType("INTEGER");

                b.Property<int?>("AudioBitRateKbps")
                    .HasColumnType("INTEGER");

                b.Property<string>("AudioBitRateMode")
                    .HasColumnType("TEXT");

                b.Property<string>("AudioChannelLayout")
                    .HasColumnType("TEXT");

                b.Property<int?>("AudioChannels")
                    .HasColumnType("INTEGER");

                b.Property<string>("AudioCodec")
                    .HasColumnType("TEXT");

                b.Property<string>("AudioCodecId")
                    .HasColumnType("TEXT");

                b.Property<string>("AudioCompressionMode")
                    .HasColumnType("TEXT");

                b.Property<bool?>("AudioDefault")
                    .HasColumnType("INTEGER");

                b.Property<string>("AudioFormatInfo")
                    .HasColumnType("TEXT");

                b.Property<string>("AudioFormatSettings")
                    .HasColumnType("TEXT");

                b.Property<double?>("AudioFrameRate")
                    .HasColumnType("REAL");

                b.Property<int?>("AudioSamplingRateHz")
                    .HasColumnType("INTEGER");

                b.Property<string>("AudioStreamId")
                    .HasColumnType("TEXT");

                b.Property<long?>("AudioStreamSizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<int?>("BitDepth")
                    .HasColumnType("INTEGER");

                b.Property<double?>("BitsPerPixelFrame")
                    .HasColumnType("REAL");

                b.Property<string>("ChromaSubsampling")
                    .HasColumnType("TEXT");

                b.Property<string>("CodecConfigurationBox")
                    .HasColumnType("TEXT");

                b.Property<string>("ColorPrimaries")
                    .HasColumnType("TEXT");

                b.Property<string>("ColorRange")
                    .HasColumnType("TEXT");

                b.Property<string>("ColorSpace")
                    .HasColumnType("TEXT");

                b.Property<string>("ContainerCodecId")
                    .HasColumnType("TEXT");

                b.Property<string>("ContainerCodecIdCompatible")
                    .HasColumnType("TEXT");

                b.Property<string>("ContainerFormat")
                    .HasColumnType("TEXT");

                b.Property<string>("ContainerFormatProfile")
                    .HasColumnType("TEXT");

                b.Property<double?>("DurationSeconds")
                    .HasColumnType("REAL");

                b.Property<string>("EncodingSettings")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("FileAddedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<long>("FileSizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<double?>("FrameRate")
                    .HasColumnType("REAL");

                b.Property<double?>("FrameRateMax")
                    .HasColumnType("REAL");

                b.Property<double?>("FrameRateMin")
                    .HasColumnType("REAL");

                b.Property<string>("FrameRateMode")
                    .HasColumnType("TEXT");

                b.Property<int?>("Height")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsPrimaryPinned")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("LastWriteUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("MatrixCoefficients")
                    .HasColumnType("TEXT");

                b.Property<string>("MediaScanError")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("MediaScannedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("OverallBitRateKbps")
                    .HasColumnType("INTEGER");

                b.Property<string>("ScanType")
                    .HasColumnType("TEXT");

                b.Property<int?>("SubtitleCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("TransferCharacteristics")
                    .HasColumnType("TEXT");

                b.Property<string>("VersionTag")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int?>("VideoBitRateKbps")
                    .HasColumnType("INTEGER");

                b.Property<string>("VideoCodec")
                    .HasColumnType("TEXT");

                b.Property<string>("VideoCodecId")
                    .HasColumnType("TEXT");

                b.Property<string>("VideoCodecIdInfo")
                    .HasColumnType("TEXT");

                b.Property<string>("VideoFormatInfo")
                    .HasColumnType("TEXT");

                b.Property<string>("VideoFormatSettings")
                    .HasColumnType("TEXT");

                b.Property<string>("VideoProfile")
                    .HasColumnType("TEXT");

                b.Property<string>("VideoStreamId")
                    .HasColumnType("TEXT");

                b.Property<long?>("VideoStreamSizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<string>("VrType")
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<bool>("VrTypePinned")
                    .HasColumnType("INTEGER");

                b.Property<int?>("Width")
                    .HasColumnType("INTEGER");

                b.Property<string>("WritingApplication")
                    .HasColumnType("TEXT");

                b.Property<string>("WritingLibrary")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("MovieId", "FileName")
                    .IsUnique();

                b.ToTable("MovieFiles");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieHighlight", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<double>("EndSeconds")
                    .HasColumnType("REAL");

                b.Property<DateTime?>("FavoritedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsFavorite")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<double>("StartSeconds")
                    .HasColumnType("REAL");

                b.Property<string>("Title")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("MovieId", "StartSeconds");

                b.ToTable("MovieHighlights");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieTag", b =>
            {
                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<int>("TagId")
                    .HasColumnType("INTEGER");

                b.Property<bool>("FromClips")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsExplicit")
                    .HasColumnType("INTEGER");

                b.HasKey("MovieId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("MovieTags");
            });

        modelBuilder.Entity("Javbuddy.Models.NfoGeneration", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("ReplacedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Trigger")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("MovieId", "ReplacedAtUtc");

                b.ToTable("NfoGenerations");
            });

        modelBuilder.Entity("Javbuddy.Models.PathMapping", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AppPrefix")
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<string>("JavinizerPrefix")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<string>("QBittorrentPrefix")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("QBittorrentPrefix")
                    .IsUnique();

                b.ToTable("PathMappings");
            });

        modelBuilder.Entity("Javbuddy.Models.ProwlarrSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ApiKey")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("BaseUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("ProwlarrSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.QBittorrentSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("BaseUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("Category")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("Password")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Username")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("QBittorrentSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.R18DevSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("DumpSourceOverride")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("LastImportSourceDate")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("LastImportSummary")
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("LastImportedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("R18DevSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.Scene", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<double?>("EndSeconds")
                    .HasColumnType("REAL");

                b.Property<DateTime?>("FavoritedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsFavorite")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsHiddenFromOverview")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<double>("StartSeconds")
                    .HasColumnType("REAL");

                b.Property<string>("Title")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("IsFavorite");

                b.HasIndex("MovieId", "StartSeconds");

                b.ToTable("Scenes");
            });

        modelBuilder.Entity("Javbuddy.Models.SceneActor", b =>
            {
                b.Property<int>("SceneId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.HasKey("SceneId", "ActorId");

                b.HasIndex("MovieId", "ActorId");

                b.ToTable("SceneActors");
            });

        modelBuilder.Entity("Javbuddy.Models.SceneEffectiveActor", b =>
            {
                b.Property<int>("SceneId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ActorId")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.HasKey("SceneId", "ActorId");

                b.HasIndex("ActorId", "SceneId");

                b.HasIndex("MovieId", "ActorId");

                b.ToTable("SceneEffectiveActors");
            });

        modelBuilder.Entity("Javbuddy.Models.SceneSuggestion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("Dismissed")
                    .HasColumnType("INTEGER");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<double>("Score")
                    .HasColumnType("REAL");

                b.Property<double>("Seconds")
                    .HasColumnType("REAL");

                b.Property<string>("Source")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("MovieId");

                b.ToTable("SceneSuggestions");
            });

        modelBuilder.Entity("Javbuddy.Models.SceneTag", b =>
            {
                b.Property<int>("SceneId")
                    .HasColumnType("INTEGER");

                b.Property<int>("TagId")
                    .HasColumnType("INTEGER");

                b.HasKey("SceneId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("SceneTags");
            });

        modelBuilder.Entity("Javbuddy.Models.ScheduledTaskRun", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("EndedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<int?>("ProgressCurrent")
                    .HasColumnType("INTEGER");

                b.Property<string>("ProgressStage")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<int?>("ProgressTotal")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("QueuedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("ResultSummary")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("StartedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("Success")
                    .HasColumnType("INTEGER");

                b.Property<string>("TaskName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("ScheduledTaskRuns");
            });

        modelBuilder.Entity("Javbuddy.Models.Tag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<bool>("NeedsReview")
                    .HasColumnType("INTEGER");

                b.Property<int?>("ParentTagId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.HasIndex("ParentTagId");

                b.ToTable("Tags");
            });

        modelBuilder.Entity("Javbuddy.Models.TagReplacementRule", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("MatchMode")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("SourceValue")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<int>("TargetTagId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TargetTagId");

                b.HasIndex("SourceValue", "MatchMode")
                    .IsUnique();

                b.ToTable("TagReplacementRules");
            });

        modelBuilder.Entity("Javbuddy.Models.TagSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("AutoIgnoreNonLatinTags")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("TagSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.TorrentDownload", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("CompletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("ContentPath")
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<long?>("DownloadSpeedBytesPerSec")
                    .HasColumnType("INTEGER");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<long?>("EtaSeconds")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("GrabbedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Hash")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Indexer")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("JavinizerBatchJobId")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("MovieCode")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<int>("MovieId")
                    .HasColumnType("INTEGER");

                b.Property<double?>("Progress")
                    .HasColumnType("REAL");

                b.Property<string>("ReleaseTitle")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("RemovedFromClientAt")
                    .HasColumnType("TEXT");

                b.Property<string>("SavePath")
                    .HasMaxLength(1000)
                    .HasColumnType("TEXT");

                b.Property<long?>("Size")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("SortedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("SourceUrl")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Hash");

                b.HasIndex("MovieId");

                b.ToTable("TorrentDownloads");
            });

        modelBuilder.Entity("Javbuddy.Models.TrickplaySet", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CodeFolder")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<double>("DurationSeconds")
                    .HasColumnType("REAL");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("GeneratedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("Height")
                    .HasColumnType("INTEGER");

                b.Property<string>("Identity")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("IntervalMs")
                    .HasColumnType("INTEGER");

                b.Property<bool>("KeyframeOnly")
                    .HasColumnType("INTEGER");

                b.Property<bool>("LeftEyeOnly")
                    .HasColumnType("INTEGER");

                b.Property<string>("SourceIdentity")
                    .HasColumnType("TEXT");

                b.Property<double>("StartSeconds")
                    .HasColumnType("REAL");

                b.Property<int>("ThumbnailCount")
                    .HasColumnType("INTEGER");

                b.Property<int>("TileHeight")
                    .HasColumnType("INTEGER");

                b.Property<int>("TileWidth")
                    .HasColumnType("INTEGER");

                b.Property<int>("Width")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CodeFolder", "Identity")
                    .IsUnique();

                b.ToTable("TrickplaySets");
            });

        modelBuilder.Entity("Javbuddy.Models.TrickplaySettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("GenerateForNewFiles")
                    .HasColumnType("INTEGER");

                b.Property<bool>("JellyfinFallback")
                    .HasColumnType("INTEGER");

                b.Property<bool>("KeyframeOnly")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("TrickplaySettings");
            });

        modelBuilder.Entity("Javbuddy.Models.WarashiSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("BaseUrl")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("LastEnrichSummary")
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("LastEnrichedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("OverwriteExisting")
                    .HasColumnType("INTEGER");

                b.Property<int>("RequestDelayMs")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("WarashiSettings");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorAlbum", b =>
            {
                b.HasOne("Javbuddy.Models.Actor", "Actor")
                    .WithMany()
                    .HasForeignKey("ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Actor");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorAlias", b =>
            {
                b.HasOne("Javbuddy.Models.Actor", "Actor")
                    .WithMany("Aliases")
                    .HasForeignKey("ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Actor");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorCupSizePeriod", b =>
            {
                b.HasOne("Javbuddy.Models.Actor", "Actor")
                    .WithMany("CupSizePeriods")
                    .HasForeignKey("ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Actor");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorPhoto", b =>
            {
                b.HasOne("Javbuddy.Models.Actor", "Actor")
                    .WithMany()
                    .HasForeignKey("ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.ActorAlbum", "Album")
                    .WithMany("Photos")
                    .HasForeignKey("AlbumId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Actor");

                b.Navigation("Album");
            });

        modelBuilder.Entity("Javbuddy.Models.ApexActor", b =>
            {
                b.HasOne("Javbuddy.Models.MovieApex", "Apex")
                    .WithMany("ApexActors")
                    .HasForeignKey("ApexId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.MovieActor", "MovieActor")
                    .WithMany()
                    .HasForeignKey("MovieId", "ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Apex");

                b.Navigation("MovieActor");
            });

        modelBuilder.Entity("Javbuddy.Models.ApexEffectiveActor", b =>
            {
                b.HasOne("Javbuddy.Models.MovieApex", "Apex")
                    .WithMany()
                    .HasForeignKey("ApexId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.MovieActor", "MovieActor")
                    .WithMany()
                    .HasForeignKey("MovieId", "ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Apex");

                b.Navigation("MovieActor");
            });

        modelBuilder.Entity("Javbuddy.Models.ApexTag", b =>
            {
                b.HasOne("Javbuddy.Models.MovieApex", "Apex")
                    .WithMany("ApexTags")
                    .HasForeignKey("ApexId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.Tag", "Tag")
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Apex");

                b.Navigation("Tag");
            });

        modelBuilder.Entity("Javbuddy.Models.HighlightActor", b =>
            {
                b.HasOne("Javbuddy.Models.MovieHighlight", "Highlight")
                    .WithMany("HighlightActors")
                    .HasForeignKey("HighlightId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.MovieActor", "MovieActor")
                    .WithMany()
                    .HasForeignKey("MovieId", "ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Highlight");

                b.Navigation("MovieActor");
            });

        modelBuilder.Entity("Javbuddy.Models.HighlightEffectiveActor", b =>
            {
                b.HasOne("Javbuddy.Models.MovieHighlight", "Highlight")
                    .WithMany()
                    .HasForeignKey("HighlightId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.MovieActor", "MovieActor")
                    .WithMany()
                    .HasForeignKey("MovieId", "ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Highlight");

                b.Navigation("MovieActor");
            });

        modelBuilder.Entity("Javbuddy.Models.HighlightTag", b =>
            {
                b.HasOne("Javbuddy.Models.MovieHighlight", "Highlight")
                    .WithMany("HighlightTags")
                    .HasForeignKey("HighlightId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.Tag", "Tag")
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Highlight");

                b.Navigation("Tag");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieActor", b =>
            {
                b.HasOne("Javbuddy.Models.Actor", "Actor")
                    .WithMany("MovieActors")
                    .HasForeignKey("ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany("MovieActors")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Actor");

                b.Navigation("Movie");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieApex", b =>
            {
                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany("Apexes")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieFile", b =>
            {
                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany("MovieFiles")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieHighlight", b =>
            {
                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany("Highlights")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieTag", b =>
            {
                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany("MovieTags")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.Tag", "Tag")
                    .WithMany("MovieTags")
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");

                b.Navigation("Tag");
            });

        modelBuilder.Entity("Javbuddy.Models.NfoGeneration", b =>
            {
                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany()
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");
            });

        modelBuilder.Entity("Javbuddy.Models.Scene", b =>
            {
                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany("Scenes")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");
            });

        modelBuilder.Entity("Javbuddy.Models.SceneActor", b =>
            {
                b.HasOne("Javbuddy.Models.Scene", "Scene")
                    .WithMany("SceneActors")
                    .HasForeignKey("SceneId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.MovieActor", "MovieActor")
                    .WithMany()
                    .HasForeignKey("MovieId", "ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("MovieActor");

                b.Navigation("Scene");
            });

        modelBuilder.Entity("Javbuddy.Models.SceneEffectiveActor", b =>
            {
                b.HasOne("Javbuddy.Models.Scene", "Scene")
                    .WithMany()
                    .HasForeignKey("SceneId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.MovieActor", "MovieActor")
                    .WithMany()
                    .HasForeignKey("MovieId", "ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("MovieActor");

                b.Navigation("Scene");
            });

        modelBuilder.Entity("Javbuddy.Models.SceneSuggestion", b =>
            {
                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany()
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");
            });

        modelBuilder.Entity("Javbuddy.Models.SceneTag", b =>
            {
                b.HasOne("Javbuddy.Models.Scene", "Scene")
                    .WithMany("SceneTags")
                    .HasForeignKey("SceneId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Javbuddy.Models.Tag", "Tag")
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Scene");

                b.Navigation("Tag");
            });

        modelBuilder.Entity("Javbuddy.Models.Tag", b =>
            {
                b.HasOne("Javbuddy.Models.Tag", "ParentTag")
                    .WithMany("Subtags")
                    .HasForeignKey("ParentTagId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ParentTag");
            });

        modelBuilder.Entity("Javbuddy.Models.TagReplacementRule", b =>
            {
                b.HasOne("Javbuddy.Models.Tag", "TargetTag")
                    .WithMany()
                    .HasForeignKey("TargetTagId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("TargetTag");
            });

        modelBuilder.Entity("Javbuddy.Models.TorrentDownload", b =>
            {
                b.HasOne("Javbuddy.Models.Movie", "Movie")
                    .WithMany()
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");
            });

        modelBuilder.Entity("Javbuddy.Models.Actor", b =>
            {
                b.Navigation("Aliases");

                b.Navigation("CupSizePeriods");

                b.Navigation("MovieActors");
            });

        modelBuilder.Entity("Javbuddy.Models.ActorAlbum", b =>
            {
                b.Navigation("Photos");
            });

        modelBuilder.Entity("Javbuddy.Models.Movie", b =>
            {
                b.Navigation("Apexes");

                b.Navigation("Highlights");

                b.Navigation("MovieActors");

                b.Navigation("MovieFiles");

                b.Navigation("MovieTags");

                b.Navigation("Scenes");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieApex", b =>
            {
                b.Navigation("ApexActors");

                b.Navigation("ApexTags");
            });

        modelBuilder.Entity("Javbuddy.Models.MovieHighlight", b =>
            {
                b.Navigation("HighlightActors");

                b.Navigation("HighlightTags");
            });

        modelBuilder.Entity("Javbuddy.Models.Scene", b =>
            {
                b.Navigation("SceneActors");

                b.Navigation("SceneTags");
            });

        modelBuilder.Entity("Javbuddy.Models.Tag", b =>
            {
                b.Navigation("MovieTags");

                b.Navigation("Subtags");
            });
#pragma warning restore 612, 618
    }
}
